apiVersion: v1
kind: Service
metadata:
  name: misp-local
  # namespace: user01-seg42
  labels:
    app: misp-local
spec:
  type: ClusterIP
  selector:
    app: pod-misp-local
  ports:    
    - name: "misp-local-http"
      protocol: TCP
      port: 80
      targetPort: 80
    - name: "misp-local-https"
      protocol: TCP
      port: 443
      targetPort: 443