apiVersion: v1
kind: Service
metadata:
  name: redis
  # namespace: user01-seg42 (Descomente se estiver usando namespace)
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: pod-redis 
  ports:
  - name: "redis-api"
    port: 6379
    targetPort: 6379