apiVersion: v1
kind: Service
metadata:
  name: cassandra
  # namespace: user01-seg42
  labels:
    app: cassandra
spec:
  type: ClusterIP
  selector:
    app: pod-cassandra
  ports:
    - name: "cassandra-port"
      protocol: TCP
      port: 7000
      targetPort: 7000