---
- name: Alterar a senha do usuário root nos hosts gerenciados
  hosts: all
  become: yes
  vars:
    new_root_password: "NovaSenhaSegura123!"  # Substitua por uma senha forte
  tasks:
    - name: Alterar a senha do usuário root
      user:
        name: root
        password: "{{ new_root_password | password_hash('sha512') }}"
        update_password: always