[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=debug

; -----------------------------
;     Geração da senha VNC
; -----------------------------
[program:setup_vnc]
command=/usr/local/bin/setup_vnc.sh
user=aluno
autostart=true
autorestart=false
priority=5
stderr_logfile=/var/log/setup_vnc.err.log
stdout_logfile=/var/log/setup_vnc.out.log

; -----------------------------
;     vfb (servidor X virtual)
; -----------------------------
[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 %(ENV_VNC_RESOLUTION)sx16 -auth /home/aluno/.Xauthority
user=aluno
autostart=true
autorestart=true
priority=10
stderr_logfile=/var/log/xvfb.err.log
stdout_logfile=/var/log/xvfb.out.log

; -----------------------------
;     XFCE (desktop)
; -----------------------------
[program:xfce]
command=/usr/bin/startxfce4
user=aluno
environment=DISPLAY=":1"
autostart=true
autorestart=true
priority=20
startsecs=5
stderr_logfile=/var/log/xfce.err.log
stdout_logfile=/var/log/xfce.out.log

; -----------------------------
;     11vnc (servidor VNC)
; -----------------------------
[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -rfbauth /home/aluno/.vnc/passwd -forever -shared -rfbport %(ENV_VNC_PORT)s -auth /home/aluno/.Xauthority
user=aluno
autostart=true
autorestart=true
priority=30
stderr_logfile=/var/log/x11vnc.err.log
stdout_logfile=/var/log/x11vnc.out.log

; -----------------------------
;    noVNC (web interface)
; -----------------------------
[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 0.0.0.0:%(ENV_NOVNC_PORT)s localhost:%(ENV_VNC_PORT)s
user=aluno
autostart=true
autorestart=true
priority=40
stderr_logfile=/var/log/novnc.err.log
stdout_logfile=/var/log/novnc.out.log
