[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=debug

; -----------------------------
;     vfb (servidor X virtual)
; -----------------------------
[program:xvfb]
command=/usr/bin/Xvfb %(ENV_DISPLAY)s -screen 0 %(ENV_VNC_RESOLUTION)sx16 -auth /home/aluno/.Xauthority
environment=DISPLAY="%(ENV_DISPLAY)s",VNC_RESOLUTION="%(ENV_VNC_RESOLUTION)s"
user=aluno
autostart=true
autorestart=true
priority=1
stderr_logfile=/var/log/xvfb.err.log
stdout_logfile=/var/log/xvfb.out.log

; -----------------------------
;     XFCE (desktop)
; -----------------------------
[program:xfce]
command=/usr/bin/startxfce4
environment=DISPLAY="%(ENV_DISPLAY)s"
user=aluno
autostart=true
autorestart=true
priority=20
startsecs=10
stderr_logfile=/var/log/xfce.err.log
stdout_logfile=/var/log/xfce.out.log

; -----------------------------
;     Geração da senha VNC e inicialização do serviço VNC
; -----------------------------
[program:setup_vnc]
command=/usr/local/bin/setup_vnc.sh
environment=VNC_PASSWORD="%(ENV_VNC_PASSWORD)s"
user=aluno
autostart=true
autorestart=false
priority=30
startsecs=10
stderr_logfile=/var/log/setup_vnc.err.log
stdout_logfile=/var/log/setup_vnc.out.log

; -----------------------------
;     11vnc (servidor VNC)
; -----------------------------
[program:x11vnc]
command=/usr/bin/x11vnc -display %(ENV_DISPLAY)s -rfbauth /home/aluno/.vnc/passwd -forever -shared -rfbport %(ENV_VNC_PORT)s -auth /home/aluno/.Xauthority
environment=DISPLAY="%(ENV_DISPLAY)s",VNC_PASSWORD="%(ENV_VNC_PASSWORD)s",VNC_PORT="%(ENV_VNC_PORT)s"
user=aluno
autostart=true
autorestart=true
priority=40
startsecs=10
stderr_logfile=/var/log/x11vnc.err.log
stdout_logfile=/var/log/x11vnc.out.log

; -----------------------------
;    noVNC (web interface)
; -----------------------------
[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 0.0.0.0:%(ENV_NOVNC_PORT)s localhost:%(ENV_VNC_PORT)s
environment=NOVNC_PORT="%(ENV_NOVNC_PORT)s",VNC_PORT="%(ENV_VNC_PORT)s"
user=aluno
autostart=true
autorestart=true
startsecs=10
priority=50
stderr_logfile=/var/log/novnc.err.log
stdout_logfile=/var/log/novnc.out.log
