apiVersion: v1
kind: Service
metadata:
  name: svc-thehive
  # namespace: user01-seg42
  labels:
    app: thehive
spec:
  type: ClusterIP 
  selector:
    app: thehive
  ports:
    - name: "thehive-https"
      protocol: TCP
      port: 443
      targetPort: 443
    - name: "thehive-ssh"
      protocol: TCP
      port: 22
      targetPort: 22