apiVersion: v1
kind: Service
metadata:
  name: thehive
  # namespace: user01-seg42
  labels:
    app: thehive
spec:
  type: ClusterIP 
  selector:
    app: pod-thehive
  ports:
    - name: "thehive-http"
      protocol: TCP
      port: 9000
      targetPort: 9000