apiVersion: v1
kind: Service
metadata:
  name: misp-modules
  # namespace: user01-seg42
  labels:
    app: misp-modules
spec:
  type: ClusterIP
  selector:
    app: pod-misp-modules
  ports:
    - name: "misp-modules-api"
      protocol: TCP
      port: 6666
      targetPort: 6666