apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  # namespace: user01-seg42
  labels:
    app: elasticsearch
spec:
  type: ClusterIP  
  selector:
    app: pod-elasticsearch
  ports:
    - name: "elasticsearch-api"
      protocol: TCP
      port: 9200
      targetPort: 9200