---
- name: Test Ansible connectivity
  hosts: all
  tasks:
    - name: Ping the nodes
      ping:

- name: Install Nginx on node1
  hosts: node1
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

- name: Install net-tools on all nodes
  hosts: nodes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install net-tools
      apt:
        name: net-tools
        state: present
