apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # namespace: user01-seg42
  labels:
    io.kompose.service: mispsqldata
  name: mispsqldata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi