apiVersion: v1
kind: Service
metadata:
  name: svc-misp-mysql
  # namespace: user01-seg42
  labels:
    app: misp-mysql
spec:
  type: ClusterIP
  selector:
    app: misp-mysql
  ports:
    - name: "mysql-data"
      protocol: TCP
      port: 3306
      targetPort: 3306