apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    #namespace: user01-seg42
    io.kompose.service: cortex-local-claim1
  name: cortex-local-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    #namespace: user01-seg42
    io.kompose.service: cortex-local-claim2
  name: cortex-local-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    #namespace: user01-seg42
    io.kompose.service: cortex-local-claim3
  name: cortex-local-claim3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi