apiVersion: v1
kind: Service
metadata:
  name: cortex-local
  # namespace: user01-seg42
  labels:
    app: cortex-local
spec:
  type: ClusterIP
  selector:
    app: pod-cortex-local
  ports:
    - name: "cortex-local-api"
      protocol: TCP
      port: 9001
      targetPort: 9001