version: '3.8'

services:
  master:
    build:
      context: ./master
    container_name: master
    hostname: master
    networks:
      ansible-net:
        ipv4_address: 172.20.0.10
    ports:
      - "2222:22"
    tty: true
    stdin_open: true
    volumes:
      - ./ansible_config:/ansible

  vm1:
    build:
      context: ./slave
    container_name: vm1
    hostname: vm1
    networks:
      ansible-net:
        ipv4_address: 172.20.0.2
    ports:
      - "2223:22"
    tty: true
    stdin_open: true

  vm2:
    build:
      context: ./slave
    container_name: vm2
    hostname: vm2
    networks:
      ansible-net:
        ipv4_address: 172.20.0.3
    ports:
      - "2224:22"
    tty: true
    stdin_open: true

networks:
  ansible-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24