apiVersion: v1
kind: Service
metadata:
  name: minio
  # namespace: user01-seg42
  labels:
    app: minio
spec:
  type: ClusterIP
  selector:
    app: pod-minio    
  ports:
    - name: "minio-api"
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: "minio-console"
      protocol: TCP
      port: 9002
      targetPort: 9002