apiVersion: v1
kind: Service
metadata:
  name: svc-minio
  # namespace: user01-seg42
  labels:
    app: minio
spec:
  type: ClusterIP
  selector:
    app: minio    
  ports:
    - name: "minio-console"
      protocol: TCP
      port: 9002
      targetPort: 9002